version: "3.8"

# $ docker compose up -d --build

services:
  client:
    build: ./frontend
    container_name: chatty_frontend
    ports:
      - "8080:80"

  service:
    build: ./backend
    container_name: chatty_backend
    # mem_limit: 2g # memory limit so container doesn't hog too much memory
    ports:
      - '7722:7722'
    volumes:
      - './backend/models:/python-docker/models'
      - './backend/data:/python-docker/data'
