version: "3.8"

# $ docker compose up -d

services:
  client:
    build: ./frontend
    container_name: chatty_frontend
    ports:
      - "8080:80"

  service:
    build: ./backend
    container_name: chatty_backend
    ports:
      - '7722:7722'
    volumes:
      - './models/output-big-elias:/python-docker/output-big-elias'
      - './models/output-big-elias-improved:/python-docker/output-big-elias-improved'
      - './models/output-trash-rick:/python-docker/output-trash-rick'
